plugins {
    id("com.android.application")
}

android {
    namespace = "com.stonx.bot"
    compileSdk = 35
    ndkVersion = "25.2.9519653"

    defaultConfig {
        applicationId = "com.stonx.bot"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        externalNativeBuild {
            cmake {
                abiFilters += listOf("arm64-v8a")
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    sourceSets {
        getByName("main") {
            // libnode.so (downloaded by the workflow) is packaged here,
            // Gradle's own native-lib pipeline handles it correctly —
            // no manual patchelf/renaming needed like the Termux route.
            jniLibs.srcDirs("libnode/bin")
        }
    }

    signingConfigs {
        create("release") {
            // Self-signed debug-style key generated by the workflow so the
            // APK is installable without any manual signing step. Fine for
            // personal/sideloaded use.
            storeFile = file("${System.getenv("HOME")}/stonx-release.keystore")
            storePassword = "stonxbot"
            keyAlias = "stonxbot"
            keyPassword = "stonxbot"
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            signingConfig = signingConfigs.getByName("release")
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {}
